cv:
#    scheme:
#    relsize_shortest_train_window:        # 1.0 is the inference dataset size
#    n_passes:
#    steps_ahead:
#    size_forecast_window:


modeling:
  approach: NaiveForwardFill
  temporal_resolution: D                      # daily resolution
  model_inference_horizon:
    start: 2013-01-01
    end:                                      # a string, unless for research purposes
      earliest_allowed: 2015-01-01
      latest_allowed: 2015-12-31
  n_splits: 6                                 # 1, unless for research purposes
  gap: 0
  forecast_horizon: 7
  preprocessing:
  hyperpars:
      trend: additive
      seasonal: multiplicative
      seasonal_periods: 7
  targets:
    - DEF0C
    - DEF07
    - DEF0B
    - DEF05
    - DEF0E


evaluation:
  - MAE
  - RMSE
  - MAPE


